/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_platform_jni_Model1 */

#ifndef _Included_com_platform_jni_Model1
#define _Included_com_platform_jni_Model1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_platform_jni_Model1
 * Method:    getmodel1
 * Signature: (CF[C)V
 */
JNIEXPORT void JNICALL Java_com_platform_jni_Model1_getmodel1
  (JNIEnv *, jobject, jchar, jfloat, jcharArray);

/*
 * Class:     com_platform_jni_Model1
 * Method:    getmodel1Object
 * Signature: (Lcom/platform/report/send/DATA1;)V
 */
JNIEXPORT void JNICALL Java_com_platform_jni_Model1_getmodel1Object
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
