/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_platform_jni_Model */

#ifndef _Included_com_platform_jni_Model
#define _Included_com_platform_jni_Model
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_platform_jni_Model
 * Method:    model1
 * Signature: (Lcom/platform/report/send/DATA1;)V
 */
JNIEXPORT void JNICALL Java_com_platform_jni_Model_model1
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_platform_jni_Model
 * Method:    model2
 * Signature: (Lcom/platform/report/send/DATA2;)V
 */
JNIEXPORT void JNICALL Java_com_platform_jni_Model_model2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_platform_jni_Model
 * Method:    model3A
 * Signature: (Lcom/platform/report/send/DATA3A;)V
 */
JNIEXPORT void JNICALL Java_com_platform_jni_Model_model3A
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_platform_jni_Model
 * Method:    model3B
 * Signature: (Lcom/platform/report/send/DATA3B;)V
 */
JNIEXPORT void JNICALL Java_com_platform_jni_Model_model3B
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_platform_jni_Model
 * Method:    model5A
 * Signature: (Lcom/platform/report/send/DATA5A;)V
 */
JNIEXPORT void JNICALL Java_com_platform_jni_Model_model5A
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_platform_jni_Model
 * Method:    model5B
 * Signature: (Lcom/platform/report/send/DATA5B;)V
 */
JNIEXPORT void JNICALL Java_com_platform_jni_Model_model5B
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_platform_jni_Model
 * Method:    model7
 * Signature: (Lcom/platform/report/send/DATA7;)V
 */
JNIEXPORT void JNICALL Java_com_platform_jni_Model_model7
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_platform_jni_Model
 * Method:    model8
 * Signature: (Lcom/platform/report/send/DATA8;)V
 */
JNIEXPORT void JNICALL Java_com_platform_jni_Model_model8
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
